### ISSUE TITLE
[00.00.00] [BUG] Salt Reactor has way too high power with the Mythic quality mod salt

### ISSUE THREAD

**Issue by dirkschut** [notnotmelon/maraxsis#108]
**Factorio & Maraxsis version number**
Factorio 2.0.24
Maraxsis 1.21.9

**Describe the bug**
With the [Mythic quality mod](https://mods.factorio.com/mod/mythic-quality) enabled (which adds 1 extra quality tier) the mythic quality salt produces 5120MJ instead of the expected 320MJ 

**To Reproduce**
1. Install Maraxsis and Mythic quality mods
2. Start new game
3. Open tech tree and search for salt reactor
4. Hover over Electricity icon in the tech
5. Behold the wrong number

**Expected behavior**
Expected value is 320MJ

**Screenshots**
![image](https://github.com/user-attachments/assets/f1521c1d-98ab-40e4-8d43-97013b9de63e)

**Additional context**
Perhaps some unintended consequence of compatibility with the infinite quality tiers mod?

**Save file & log**
NA

**Comment by notnotmelon** [comment]
After some investigation it seems the quality levels in the mythic quality mod follow some suspicious pattern:

normal: level = 1
uncommon: level = 2
rare: level = 3
epic: level = 4
legendary: level = 5
mythic: level = 10

The salt formula is 2^N, so you can see the issue.

I'm going to mark this as "not a bug", the formula is working as intended, the issue is that this mod has broken the pattern.
