### ISSUE TITLE
[1.22.0] [FEAT] Make sealant production easier

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#123]
**Is your feature request related to a problem? Please describe.**
The production of super sealant to be able to use the rocket silo is very convoluted. Since the mod forbids unbarreling heavy oil (which there are seas of on Fulgora), you need to do coal synthesis->simple coal liquefaction with sulfuric acid to get a bit of heavy oil->advanced coal liquefaction and then get some steam somewhere in space which means only one thing: nuclear.

We use fusion ships, so that is a bit jarring. Any way to make that a little less convoluted? This means a dedicated platform just to do this. 

**Describe the solution you'd like**
Allow us to make sealant anywhere.

**Comment by tylercd100** [comment]
I think the intention is add another reason to use space platforms as a factory as the only other use case for a factory in space is space science. (I get that there are other things you can do with platforms but for progression in the game, they can be ignored. i.e. legendary coal production in space is not needed to complete the game)

Maraxsis is unlockable at the same time as aquilo but not after aquilo, meaning that for a fresh playthrough a typical player may not have fusion power yet.

Maraxsis is also on the same level as aquilo, meaning it already requires planetary logistics to complete. so bringing over some nuclear fuel cells doesn't seem to be out of the question.

Some things that were discussed on discord:
- Unbanning heat towers in space -> would break the meta for power generation in space, why use anything other than a heat tower?
- Add uranium to Maraxsis/Trench -> would remove the uniqueness of Nauvis (biolabs have already been unbanned for other planets on this mod)

I guess what we need to ask is: Is this additional puzzle fun and is it difficult enough to justify the rewards of maraxsis? How does it compare to the fun and difficulty of aquilo? (i.e. why should i choose to go to maraxsis first instead of aquilo?)

**Comment by Andargor** [comment]
We managed to hack one of our workhorses to produce some sealant. Was it fun? Hrm.

I think I would rather see some unique materials from Maraxsis to produce the sealant locally, instead of modifying or limiting vanilla recipes.

**Comment by notnotmelon** [comment]
The heavy oil embargo has been lifted!
You can now unbarrel in space.

Additionally I have added a new recipe that allows to recycle extra petrol. So if you decide to make it in space anyway, you are rewarded a bit.
![image](https://github.com/user-attachments/assets/8c884d11-f1c2-4bae-9ca0-714d336a9890)

**Comment by boomshroom** [comment]
Getting around the heavy oil restriction was a little annoying, but not too bad since you can jumpstart it with simple coal liquefaction and imported calcite and sulfuric acid.

The real thing that's annoying with sealant is how it forces you into a nuclear fission reactor. I was honestly considering using one of the mods that adds a steam recipe in space just so that I could use other power sources, most notably the new salt reactor, which looks really cool and interesting, but I'm having trouble finding a niche for it beyond ships going between Nauvis and Maraxsis anyways due to heating towers being as OP as they are. (Infinite free energy anywhere except space, for comparable space as nuclear, with fusion's main benefit being the much smaller footprint at the cost of more complex interplanetary logistics).

Unbanning the heating tower in space would be a terrible decision if you ask me because it's already so OP as it is that it needs to leave _some_ niche open to other power sources. I'd much rather have a new way to make steam in space that's usable for coal liquefaction and sealant, but is too cool to realistically use for power.

**Comment by Andargor** [comment]
Or have a separate recipe that doesn't use steam, but requires something from Maraxsis, like brine or something. So the first time you have the trouble of making sealant with a reactor, but then afterwards you are rewarded with a better recipe once you can launch the rocket.
