### ISSUE TITLE
[24.12.14] [BUG] Adding a zero-quanity item to a submarine logistic group causes corruption of logistic group

### ISSUE THREAD

**Issue by hikeonpast** [notnotmelon/maraxsis#150]
**Factorio & Maraxsis version number**
Factorio 2.0.23 win64
Maraxsis 1.23.43

**Describe the bug**
Adding a zero-quantity item to a logistic group in a (construction) submarine causes:
1) the zero-quantity item to disappear from the logistic group after a second or two
2) logistic groups to become corrupted by that submarine.  I can't spot the pattern, but I've witnessed cross-pollination, where specific slots from other logistic groups are copied to the top group, but they don't overwrite anything in an existing slot within that group.

**To Reproduce**
1. Build a construction submarine
2. Open the item detail
3. Make a group with a positive request item, like fuel
4. Add an item with zero quantity, like empty barrels

**Comment by Andargor** [comment]
It might be related to the Constructron issue where the first logistic group MUST exist and not be used. The mod will change it according to needs, and they won't fix it because of some engine limitations. See here: https://github.com/notnotmelon/maraxsis/issues/125

I use this configuration successfully in construction subs for fuel management:

![gkWegQq](https://github.com/user-attachments/assets/c37f4bc2-6572-4b01-af9b-0f602cb15e82)

**Comment by hikeonpast** [comment]
Yep, it's the same issue.  Since it's downstream from SpidertonPatrols with engine limitations, perhaps this ticket becomes an enhancement request for improved documentation around Construction Submarines and ways to work around the landmines from upstream code.  

At the user level, this is pretty icky to get hit with, particularly because logistic groups are global across all planets, platforms, vehicles, etc.

**Comment by Fr-Dae** [comment]
the [00.00.00] should be the date in iso 8601 format in title
