### ISSUE TITLE
[24.12.14] [BUG] Construction submarines always want to go to their favorite regulator

### ISSUE THREAD

**Issue by hikeonpast** [notnotmelon/maraxsis#152]
**Factorio & Maraxsis version number**
Factorio 2.0.23 win64
Maraxsis 1.23.43

**Describe the bug**
Construction submarine constantly sets its own temporary waypoint at a specific regulator.   The sub can be in manual mode or even in Drive Remotely mode it will never stay stationary, always homing to one specific regulator.  Does not seem to be an issue with non-construction subs.

**To Reproduce**
1) build a construction submarine, add to the grid power and a roboport
2) the submarine immediately moves toward a specific dome/regulator
3) with the sub in manual mode, set a temporary waypoint on the edge of the screen
4) observe the sub go to that waypoint and immediately return to its favorite dome/regulator

**Expected behavior**
I think the intent is that sub navigation is like spidertron navigation.   I can direct a Spidertron to go to a location and stay there.  Can't do that with construction subs.

**Comment by notnotmelon** [comment]
Construction submarines are heavily scripted. The code is based on this project:
https://mods.factorio.com/mod/Constructron-Continued?from=search

The logic of a construction submarine is to go to the regulator, collect all construction materials, and build ghosts for any entity on the entire map. They are intended to be fully automated without need to manual editing with the waypoints.

For this reason, I believe your bug is actually a feature. Perhaps the central issue here is actually a lack of documentation on how the construction submarines are intended to function.

**Comment by hikeonpast** [comment]
That sounds super cool.  As a test, I've got a construction submarine with an equipment grid consisting of power, roboports, and exoskeletons.  Its quiescent at the (first built) regulator.  If I go to an outpost and build some ghosts, using assets that are known to be in-network to the regulator, I don't see it collecting the construction materials, regardless of manual/auto setting. Under Details, it shows a task at the "job location", but for some reason it's not requisitioning the materials for the ghosts at that location.
