### ISSUE TITLE
Unusable Rocket/Nuclear Fuel in other modded vehicles

### ISSUE THREAD

**Issue by swoleprole** [notnotmelon/maraxsis#170]
**Factorio & Maraxsis version number**
Factorio 2.0.26 (build 81022 expansion, win64) ; Maraxis 1.24.7

**Describe the bug**
Modded vehicles (Aircraft, AAI vehicles) are unable to accept Rocket and Nuclear Fuel to burn. Vanilla vehicles seemingly unaffected. 

**To Reproduce**
Nothing to do to make it happen, it is just like this. 

**Expected behavior**
I expect to be able to burn Rocket/Nuclear Fuel in modded vehicles. (They're the best ones, obviously.)

**Screenshots**
![Tank](https://github.com/user-attachments/assets/90179c98-2109-4522-98de-047b0fc0f33b)
![Jet](https://github.com/user-attachments/assets/aaed0195-5171-4aa4-ab62-a0579b79eaf4)
![AAI Hauler](https://github.com/user-attachments/assets/c3b8f701-9dec-489e-8b44-25fd5ab40b06)

**Additional context**
I noticed this issue after the Maraxsis update that changed values for burning barreled oil as fuel. If I remove Maraxsis from the save, I'm able to properly burn those fuels in vehicles again. 

**Save file & log**
[factorio-current.log](https://github.com/user-attachments/files/18186408/factorio-current.log)

GitHub says my save file is too large to upload. Please advise on workaround.

**Comment by nicholasgower** [comment]
I believe that the problem is in data-final-fixes.lua, where rocket fuel and nuclear fuel are moved from "chemical" fuel category to their own fuel type, and all vehicles that take chemical fuel are given access to these fuel types.


`data.raw.item["rocket-fuel"].fuel_category = "rocket-fuel"
data.raw.item["nuclear-fuel"].fuel_category = "nuclear-fuel"

for entity_type in pairs(defines.prototypes.entity) do
    for _, entity in pairs(data.raw[entity_type] or {}) do
        local burner = entity.burner or entity.energy_source
        if not burner then goto continue end
        if burner.type ~= "burner" then goto continue end
        if table.find(burner.fuel_categories or {}, "chemical") then
            table.insert(burner.fuel_categories, "rocket-fuel")
            table.insert(burner.fuel_categories, "nuclear-fuel")
        end`



For some reason, this line of code doesn't detect vehicles that have fuel_categories blank. It only checks vehicles with the fuel category explicitly set to "chemical." Modders can issue their own patches to make their use of chemical fuel more explicit, but this is also something that this mod needs to address to make those kinds of patches unnecessary. I'll make a patch to Aircraft to fix the issue on my end in the meantime.
