### ISSUE TITLE
Placeholder graphics for the coral reef.

### ISSUE THREAD

**Issue by notnotmelon** [notnotmelon/maraxsis#6]

**Comment by snouz** [comment]
Hi, I could work on this if you're interested. I just finished SA and I want to get back into modding : )

Here's what I did in factorio previously:

https://mods.factorio.com/mod/MbrTestMod

**Comment by solarcloud7** [comment]
Wow these look awesome!   I know no one cares but you have my vote of confidence :D

**Comment by notnotmelon** [comment]
That's incredible. I've seen your portfolio before and it's very impressive. Thanks for the offer!

But...

![coral-anim-1](https://github.com/user-attachments/assets/6ebea0c1-9858-497f-88bf-5bccc889edf5)

I am happy to work with you on fixing other placeholder graphics. Would you like to work on the Maraxsis enemy?

**Comment by snouz** [comment]
Ah I didn't know you had some already ready, I just noticed the placeholder as I started Maraxsis. I did not go further yet, I just checked out the tech tree, the surface, and told myself I'm gonna do the mod later because apparently that needs to be completed before you can resume the last vanilla research.

I don't know if I'll be able to create an enemy from scratch, since they might require 3D work to exist in all directions, and I have no experience outside of 2D graphics. But if you're interested by any graphics from this, you can go ahead, the update ended up never releasing

https://mods.factorio.com/mod/Bio_Industries_NE_graphics

For exemple, I was pretty happy with that one

![image](https://github.com/user-attachments/assets/0dab46f4-bf8b-4da0-9413-b21cfc27e079)

with an animated glow and trees, which could serve to stabilize the atmosphere of domes later for example

Or any other icon/entity
